v_front_index:
    path:     /e
    defaults: { _controller: VFrontBundle:Main:index }
v_front_cart:
    path:     /c
    defaults: { _controller: VFrontBundle:Main:cart }
v_front_comm:
    path:     /comm
    defaults: { _controller: VFrontBundle:Main:comm }
v_front_livr:
        path:     /liv
        defaults: { _controller: VFrontBundle:Main:livr }

